version: "3.9"

services:
  db:
    image: postgres:alpine3.17
    container_name: yt_db
    env_file:
      - .env
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    container_name: dmkh_bot
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    restart: on-failure
    entrypoint: poetry run python3 -m bot
  lab:
    build:
      context: .
      dockerfile: docker/lab.Dockerfile
    container_name: study_lab
    env_file:
      - .env
    environment:
      POSTGRES_HOST: yt_db
    ports:
      - "${LAB_PORT}:${LAB_PORT}"
    volumes:
      - ./data:/app/data
    entrypoint: jupyter lab --ip=0.0.0.0 --port=${LAB_PORT} --no-browser --allow-root