version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    container_name: dmkh_bot
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    entrypoint: poetry run python3 -m bot
  lab:
    build:
      context: .
      dockerfile: docker/lab.Dockerfile
    container_name: study_lab
    ports:
      - "${LAB_PORT}:${LAB_PORT}"
    volumes:
      - ./data:/app/data
    entrypoint: jupyter lab --ip=0.0.0.0 --port=${LAB_PORT} --no-browser --allow-root