version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    container_name: dmkh_bot
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    entrypoint: poetry run python3 -m bot