"""reinit

Revision ID: 3ef1cd8ecfef
Revises: e186adbfc0ce
Create Date: 2023-11-21 23:56:03.668224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef1cd8ecfef'
down_revision: Union[str, None] = 'e186adbfc0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_users', 'reg_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('playlists', sa.Column('playlist_name', sa.String(), nullable=False))
    op.alter_column('playlists', 'link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('playlists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('playlists', 'reg_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tracks', 'playlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tracks', 'track_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tracks', 'track_tg_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tracks', 'track_thumbnail',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tracks', 'performer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tracks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tracks', 'reg_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint('tracks_user_id_fkey', 'tracks', type_='foreignkey')
    op.drop_column('tracks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tracks_user_id_fkey', 'tracks', 'bot_users', ['user_id'], ['id'])
    op.alter_column('tracks', 'reg_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tracks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tracks', 'performer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tracks', 'track_thumbnail',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tracks', 'track_tg_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tracks', 'track_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tracks', 'playlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playlists', 'reg_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('playlists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('playlists', 'link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('playlists', 'playlist_name')
    op.alter_column('bot_users', 'reg_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
