"""init

Revision ID: 868a78757f5c
Revises: 
Create Date: 2023-11-16 10:02:11.951409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868a78757f5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('status', sa.VARCHAR(length=5), nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('playlists',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('playlist_id'),
    sa.UniqueConstraint('playlist_id')
    )
    op.create_table('tracks',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_link', sa.Text(), nullable=False),
    sa.Column('track_tg_id', sa.Text(), nullable=False),
    sa.Column('track_thumbnail', sa.Text(), nullable=False),
    sa.Column('performer', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.playlist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('playlists')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
