"""thumbnail

Revision ID: 8f4a92f6824d
Revises: 3ef1cd8ecfef
Create Date: 2023-11-28 12:52:27.761593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4a92f6824d'
down_revision: Union[str, None] = '3ef1cd8ecfef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'track_thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'track_thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
